server:
  port: 8002

spring:
  #  datasource:
  #    username: root
  #    password: zyf-zyf111222333
  #    url: jdbc:mysql://10.154.122.99:3306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
  #      connection-test-query: select 1
  #      connection-timeout: 20000
  #      idle-timeout: 300000
  #      maximum-pool-size: 5
  #      minimum-idle: 5
  datasource:
    # shardingsphere 对 Driver 自定义，实现分库分表
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # shardingsphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 10.154.122.99
      port: 6379
      password: zyf-zyf111222333
